version: "3.9"

services:
  redis:
    build:
      context: ./src/cache
    container_name: redis-container
    ports:
      - 6379
    networks:
      - redis_network

  db:
    image: postgres
    container_name: postgres-container
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432
    networks:
      - redis_network

  adminer:
    image: adminer
    container_name: adminer-container
    restart: always
    ports:
      - 8080

  fastapi:
    build:
      context: .
    depends_on:
      - db
      - redis
    #container_name: fastapi-container-1
    ports:
      - 8080
    networks:
      - redis_network

  nginx:
    build:
      context: ./load_balancer
    container_name: nginx
    ports:
      - 80:80
    depends_on:
      - fastapi
    networks:
      - redis_network

volumes:
  redis_data:

networks:
  redis_network:
